# This workflow installs node dependencies, caches them, builds the source code, and runs tests across different versions of Node.js.
# It is configured to trigger on pushes and pull requests to the 'main' branch.

name: Node.js CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # This will run the build and tests on Node.js versions 18.x, 20.x, and 22.x

    steps:
    - uses: actions/checkout@v4
      # Check out the repository code

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      # Set up Node.js environment and cache npm dependencies

    - run: npm ci
      # Install dependencies using npm ci (clean install)

    - run: npm run build --if-present
      # Build the React application if the build script is defined

    - run: npm test
      # Run tests defined in the project
